### ISSUE TITLE
test with real IdPs

### ISSUE THREAD

**Issue by pdavide** [italia/spid-laravel#3]
Currently this package is confirmed to work the idp.spid.gov.it:9443 identity provider.
We need to test it with real idps.

**Comment by i1990jain** [comment]
I have added the spid-laravel package, and was also able to test using the idp.spid.gov.it:9443 
but since a while it is not possible to authenticate using the same. Any idea why is that happening?

**Comment by pdavide** [comment]
Hi @i1990jain,
for testing purposes please refer to https://github.com/italia/spid-testenv2 and no more to idp.spid.gov.it:9443 (not officially supported).
Additionally consider that this package will be soon updated to use https://github.com/italia/spid-php-lib/ and drop any other external dependency.
