### ISSUE TITLE
What version of laravel is supported?

### ISSUE THREAD

**Issue by wannymiarelli** [italia/spid-laravel#42]
Seems like this package uses some deprecated classes, for example, the DetectsApplicationNamespace trait has been removed from Laravel 7.0. Is support for Laravel 7.0 planned? Do you accept PR? I can probably take care of that.

**Comment by pdavide** [comment]
Hi @wannymiarelli, currently this package is missing support for Laravel 7.
If you want to contribute any help is appreciated.

@axciccu are you on this too?

**Comment by axciccu** [comment]
> Hi @wannymiarelli, currently this package is missing support for Laravel 7.
> If you want to contribute any help is appreciated.
> 
> @axciccu are you on this too?

Hi, yes. 
Seems like that the solution can be to change this line

https://github.com/italia/spid-laravel/blob/919e7de4d2231beab2bf5160d0a1a923ee205f9a/src/Console/CommandExample.php#L124

with
Container::getInstance()->getNamespace().

I'm going to open a Pull request

**Comment by pdavide** [comment]
Closed in #43.
