### ISSUE TITLE
Failed Autentication Spid PosteID Level II

### ISSUE THREAD

**Issue by marcodadamo** [italia/spid-laravel#54]
With **SPID POSTE** ID during authentication I enter the user name, password I click on login, From the moment I receive the **SMS** with the code and I insert it in the text field the message login failed appears. The message appears every time I try to authenticate.

**Comment by pdavide** [comment]
Hi @marcodadamo,
this issue seems to be located on the IdP side. spid-laravel is a package for the SP side.
Feel free to re-open if you think there is a problem on the SP side related to the spid-laravel package and you can provide more details about the error.

**Comment by marcodadamo** [comment]
Ok thanks. Open [issue](https://github.com/italia/spid-idp-login-layout/issues/6)
