### ISSUE TITLE
Invalid Issuer Tag Value - AuthRequest Xml 

### ISSUE THREAD

**Issue by MarcoBevilacqua** [italia/spid-laravel#57]
Ciao a tutti, 

abbiamo ricevuto parere negativo sulla richiesta di accreditamento a causa di una mancata validazione sulla SAML request:

![image](https://user-images.githubusercontent.com/3083440/106287657-53057a00-6247-11eb-951d-5a539a7caefd.png)

il valore all'interno del tag Issuer contiene degli spazi e caratteri newLine che impediscono la validazione (il contenuto del tag dovrebbe essere uguale all'entityID, che non contiene caratteri speciali). 

I caratteri "indesiderati" sono inseriti nel file AuthnRequest.php della libreria onelogin.

![image](https://user-images.githubusercontent.com/3083440/106288863-d96e8b80-6248-11eb-84cb-ea17c74296cb.png)

Qualcuno ha già avuto questo problema? Ho provato a customizzare l'xml con un semplice replace ma non ci sono riuscito.
É possibile farlo?

Grazie

**Comment by pdavide** [comment]
Ciao @MarcoBevilacqua,
per la problematica che segnali, penso che la strada sia quella di aggiornare la [patch](https://github.com/italia/spid-laravel/blob/master/patches/php-saml-3.4.1-spid.patch) applicata a `php-saml` in modo da non avere spazi all'interno del tag `Issuer`.

Dovrebbe essere un'operazione abbastanza semplice, se vuoi contribuire con una PR sarebbe molto gradito.

**Comment by chech66** [comment]
Scusatemi, se mi intrometto anche qui, ma sto' passando le medesime problematiche degli altri. Per il momento non ho il modo di modificare la patch, pero' sono riuscito a passare il test, copiando brutalmente nel file AuthnRequest.php (dalla riga 164, attualmente), modificando quanto scritto da @MarcoBevilacqua in:

<saml:Issuer
        NameQualifier="{$spEntityId}"
        Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">{$spEntityId}</saml:Issuer>

mi rendo conto che e' una soluzione non molto pratica perche' basta un semplice composer update al progetto, per essere daccapo.

**Comment by chech66** [comment]
Non si potrebbe cambiare la patch (verificata la correttezza) da:

@@ -151,12 +150,19 @@ REQUESTEDAUTHN;
     xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
     ID="$id"
     Version="2.0"
-{$providerNameStr}{$forceAuthnStr}{$isPassiveStr}
+{$forceAuthnStr}{$isPassiveStr}
     IssueInstant="$issueInstant"
-    Destination="{$idpData['singleSignOnService']['url']}"
+    Destination="{$idpData['entityId']}"
     ProtocolBinding="{$spData['assertionConsumerService']['binding']}"
-    AssertionConsumerServiceURL="{$acsUrl}">
-    <saml:Issuer>{$spEntityId}</saml:Issuer>{$subjectStr}{$nameIdPolicyStr}{$requestedAuthnStr}
+    AssertionConsumerServiceURL="{$acsUrl}"
+    AttributeConsumingServiceIndex="0">
+    <saml:Issuer
+        NameQualifier="{$spEntityId}"
+        Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">
+        {$spEntityId}
+    </saml:Issuer>
+{$nameIdPolicyStr}
+{$requestedAuthnStr}
 </samlp:AuthnRequest>
 AUTHNREQUEST;

a

@@ -151,12 +150,19 @@ REQUESTEDAUTHN;
     xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
     ID="$id"
     Version="2.0"
-{$providerNameStr}{$forceAuthnStr}{$isPassiveStr}
+{$forceAuthnStr}{$isPassiveStr}
     IssueInstant="$issueInstant"
-    Destination="{$idpData['singleSignOnService']['url']}"
+    Destination="{$idpData['entityId']}"
     ProtocolBinding="{$spData['assertionConsumerService']['binding']}"
-    AssertionConsumerServiceURL="{$acsUrl}">
-    <saml:Issuer>{$spEntityId}</saml:Issuer>{$subjectStr}{$nameIdPolicyStr}{$requestedAuthnStr}
+    AssertionConsumerServiceURL="{$acsUrl}"
+    AttributeConsumingServiceIndex="0">
+    <saml:Issuer
+        NameQualifier="{$spEntityId}"
+        Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">{$spEntityId}</saml:Issuer>
+{$nameIdPolicyStr}
+{$requestedAuthnStr}
 </samlp:AuthnRequest>
 AUTHNREQUEST;

**Comment by chech66** [comment]
Scusate l'inesperienza:
da 

`@@ -151,12 +150,19 @@ REQUESTEDAUTHN;
     xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
     ID="$id"
     Version="2.0"
-{$providerNameStr}{$forceAuthnStr}{$isPassiveStr}
+{$forceAuthnStr}{$isPassiveStr}
     IssueInstant="$issueInstant"
-    Destination="{$idpData['singleSignOnService']['url']}"
+    Destination="{$idpData['entityId']}"
     ProtocolBinding="{$spData['assertionConsumerService']['binding']}"
-    AssertionConsumerServiceURL="{$acsUrl}">
-    <saml:Issuer>{$spEntityId}</saml:Issuer>{$subjectStr}{$nameIdPolicyStr}{$requestedAuthnStr}
+    AssertionConsumerServiceURL="{$acsUrl}"
+    AttributeConsumingServiceIndex="0">
+    <saml:Issuer
+        NameQualifier="{$spEntityId}"
+        Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">
+        {$spEntityId}
+    </saml:Issuer>
+{$nameIdPolicyStr}
+{$requestedAuthnStr}
 </samlp:AuthnRequest>
 AUTHNREQUEST;`

a

`@@ -151,12 +150,19 @@ REQUESTEDAUTHN;
     xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
     ID="$id"
     Version="2.0"
-{$providerNameStr}{$forceAuthnStr}{$isPassiveStr}
+{$forceAuthnStr}{$isPassiveStr}
     IssueInstant="$issueInstant"
-    Destination="{$idpData['singleSignOnService']['url']}"
+    Destination="{$idpData['entityId']}"
     ProtocolBinding="{$spData['assertionConsumerService']['binding']}"
-    AssertionConsumerServiceURL="{$acsUrl}">
-    <saml:Issuer>{$spEntityId}</saml:Issuer>{$subjectStr}{$nameIdPolicyStr}{$requestedAuthnStr}
+    AssertionConsumerServiceURL="{$acsUrl}"
+    AttributeConsumingServiceIndex="0">
+    <saml:Issuer
+        NameQualifier="{$spEntityId}"
+        Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">{$spEntityId}</saml:Issuer>
+{$nameIdPolicyStr}
+{$requestedAuthnStr}
 </samlp:AuthnRequest>
 AUTHNREQUEST;`

**Comment by pdavide** [comment]
Ciao @chech66, come [scrivevo prima](https://github.com/italia/spid-laravel/issues/57#issuecomment-770007727), mi sembra che la soluzione sia proprio quella di modificare la patch.
Potresti contribuire con una PR?

**Comment by chech66** [comment]
Non conosco git... sto mettendo la patch, se qualcuno piu' esperto la puo' applicare.

credo che debba cambiare da:
![da](https://user-images.githubusercontent.com/43406075/113844787-24e76d80-9795-11eb-82ba-3c4a228b38d4.png)
a
![a](https://user-images.githubusercontent.com/43406075/113844832-33358980-9795-11eb-86b1-6c1a0a209714.png)

in rosso la modifica
