### ISSUE TITLE
Section incompatibili con con il design-laravel-theme italia

### ISSUE THREAD

**Issue by Losa90** [italia/spid-laravel#62]
Nel file spid-button.blade.php ci sono due `@push` che fanno riferimento a "styles" e "scripts", ma utilizzando il tema ufficiale https://github.com/italia/design-laravel-theme le sezioni non esistono, vegono invece usate "css" e "js". Di conseguenza non vengono caricate le risorse corrette e il bottone non funziona.
Modificando `@push('styles')` in `@push('css')` e `@push('scripts')` in `@push('js')` funziona.

**Comment by pdavide** [comment]
Ciao @Losa90,
questa libreria e il tema https://github.com/italia/design-laravel-theme non sono progetti correlati e non necessariamente vanno usati insieme. Inoltre nessuno dei due ha carattere di "ufficialità" ma si tratta di strumenti messi a disposizione dalla community per la community.
L'onere dell'integrazione tra progetti/librerie differenti è a carico dello sviluppatore, quindi non è opportuno modificare le librerie per cercare di adattarle alle singole esigenze.

Nello specifico caso che hai descritto, penso sia sufficiente inserire una direttiva `@stack('styles')` dentro la `@section('css')` e una direttiva `@stack('scripts')` dentro la `@section('js')`.
