### ISSUE TITLE
spid validator non passa il Request Check Strict: Test the compliance of RelayState parameter

### ISSUE THREAD

**Issue by chech66** [italia/spid-laravel#65]
Morta una issue ne nasce un'altra.
Sto' effettuando i controlli con lo spid validator e mi sono imbattuto nel fallimento del test sul RelayState.
"RelayState must non be immediately intelligible - TR pag. 14 or pag. 15" nei test Request/Check Strict/RelayState.
Magari il servizio viene validato lo stesso nella realta', pero' dovendo effettuare ancora la richiesta, preferirei che i test fossero tutti positivi.
 
Il ReayState contiene l'url della login:"https://www.pincopalla.it/spid/login", a quanto pare non si vuole che sia comprensibile agli IdP questo campo, per motivi di privacy.

Sono andato a vedere la Auth.php in onelogin/php-saml. Alla riga 554 circa  c'e' la
$parameters['RelayState'] = Utils::getSelfRoutedURLNoQuery();

l'ho modificata, per provare, in:
$parameters['RelayState'] = "token"; ma si perderebbe l'url.

oppure si puo' crittografare la stringa Utils::getSelfRoutedURLNoQuery(), in modo da poterla recuperare in un secondo momento.

Sembra che cosi' il test venga passato e sembrerebbe funzionare tutto quanto, pero' non so se il RelayState venga poi utilizzato nel codice dopo la login per uno scopo.

**Comment by pdavide** [comment]
@chech66 a mio parere un campo `RelayState` che contiene un URL che corrisponde all'endpoint del SSO non ha alcuna necessità di essere modificato perché contiene dati pubblici e non riconducibili in alcun modo al servizio specifico per il quale l'utente si sta autenticando.

D'altro canto, il campo `RelayState` non è usato in questo package, perché le informazioni relative alla pagina richiesta dall'utente sono eventualmente memorizzate nella sessione. Quindi, se vuoi provare a impostare `RelayState` a una stringa vuota, puoi semplicemente a modificare il primo parametro di questa chiamata da `null` a `''`:
https://github.com/italia/spid-laravel/blob/15131905b635dc26049e49f29acfaebd89585199/src/SPIDAuth.php#L66

Se in questo caso non riscontri problemi di validazione puoi anche proporre la modifica come nuova PR.
