### ISSUE TITLE
package issue

### ISSUE THREAD

**Issue by Asifkrishaweb** [italia/spid-laravel#66]
composer require italia/spid-laravel
when installing a package

Problem 1
    - Root composer.json requires italia/spid-laravel ^0.2.0@beta -> satisfiable by italia/spid-laravel[v0.2.0-beta].
    - italia/spid-laravel v0.2.0-beta requires illuminate/config ~5.0 -> found illuminate/config[v5.0.0, ..., v5.8.36] but it conflicts with your root composer.json require (>=6.0).

**Comment by pdavide** [comment]
Hi @Asifkrishaweb,
the version you are trying to install ([v0.2.0-beta](https://github.com/italia/spid-laravel/releases/tag/v0.2.0-beta)) is quite old and marked as "pre-release".
Please, try to install the latest version.

`composer require italia/spid-laravel` should pick the latest version, but you can also be more specific including the version number you require in the command like `composer require "italia/spid-laravel:^1.2@beta"`.

Feel free to re-open in case you think there is bug in this package.

**Comment by Asifkrishaweb** [comment]
i install and it's work

can you please tell me why this  error is coming

Malformed request: idp value not present or wrong (this is likely due to a
non-https request)

when i clicked on login with SPID button
