### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Asifkrishaweb** [italia/spid-laravel#68]
when i clicked on "login with spid"  and it redirect me to spid/login page where there is a list of service providers 
when i clicked on one of them following error is occured

Namirial.ID - Incorrect request format. 
ErrorCode nr10
Contact the service manager

Please help for the same

Thanks in advance

**Comment by pdavide** [comment]
You can only use an official IdP if your organization has a metadata approved and deployed by AGID. Please refer to the official documentation: https://www.spid.gov.it/come-diventare-fornitore-di-servizi-pubblici-e-privati-con-spid.
If you need a testing environment you can take a look at https://www.spid.gov.it/come-diventare-fornitore-di-servizi-pubblici-e-privati-con-spid. In case you need to request approval for a new service provider you may also look at https://github.com/italia/spid-saml-check.
I suggest to read carefully the SPID technical rules at https://docs.italia.it/italia/spid/spid-regole-tecniche/it/stabile/index.html.

**Comment by Asifkrishaweb** [comment]
Actually i only need button for login to SPID in my project 
when user want login with SPID they can proceed.
that's it

**Comment by Asifkrishaweb** [comment]
any credentials shoud l i need to add in my config file for integration of SPID login ?

please help for the same

**Comment by Asifkrishaweb** [comment]
[image: Screenshot from 2021-04-13 13-10-09.png]
in above image creating a link <a> when click on providers list

but below image has a button not a link , may you please help for the same.
[image: Screenshot from 2021-04-13 13-10-43.png]

**Comment by pdavide** [comment]
Hi @Asifkrishaweb,
issues are not intended for support requests.

Please refer to the SPID community at https://developersitalia.slack.com/messages/C73R3UQE8.
