### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Asifkrishaweb** [italia/spid-laravel#69]
Hello
what should i need to do for test SPID authentication in testing envrionment

kindly help

thank you

**Comment by pdavide** [comment]
Hi @Asifkrishaweb,
as [I wrote in another issue](https://github.com/italia/spid-laravel/issues/68#issuecomment-818653788), this space is not intended for support requests.

Please refer to the SPID community at https://developersitalia.slack.com/messages/C73R3UQE8.

**Comment by Asifkrishaweb** [comment]
http://localhost:8000/spid/acs
URL return below error

Malformed request: idp value not present or wrong (this is likely due to a non-https request)

please help for the same
