### ISSUE TITLE
spid/acs

### ISSUE THREAD

**Issue by Asifkrishaweb** [italia/spid-laravel#71]
spid/acs  url return 

The GET method is not supported for this route. Supported methods: POST.

how can i manage

please help for the same

Thank you

**Comment by pdavide** [comment]
Hi @Asifkrishaweb,
as I wrote in another issue, this space is not intended for support requests.

As can you read in the readme, this package supports http-post binding only.

Please refer to the SPID community at https://developersitalia.slack.com/messages/C73R3UQE8.

**Comment by Asifkrishaweb** [comment]
Hello

post request : http://localhost:8000/spid/acs

Malformed request: idp value not present or wrong (this is likely due to a non-https request)

please help
Thank you

**Comment by Asifkrishaweb** [comment]
spid/acs post request

[image: Screenshot from 2021-04-20 11-16-09.png]
showing something like that
and
when  i click on send button it return following error
[image: Screenshot from 2021-04-20 10-28-26.png]

please help for the same
thank you
