### ISSUE TITLE
Could not find package italia/spid-laravel in a specific version

### ISSUE THREAD

**Issue by nicolastorgato** [italia/spid-laravel#74]
Ciao, 

ho riscontrato lo stesso problema della issue #66, ma anche provando ad installare una specifica versione del pacchetto (come suggerito nella risposta), ricevo questo errore: 
[InvalidArgumentException]
Could not find package italia/spid-laravel in a version matching 1.2@beta

Specifico che ho dato questo comando: composer require "italia/spid-laravel:^1.2@beta"

Perchè senza specificare la versione non viene presa la latest release (come invece dovrebbe accadere)???
Come posso risolvere? 
Grazie!

**Comment by pdavide** [comment]
Ciao @nicolastorgato,
se provo a eseguire questa sequenza di comandi in una directory vuota non ottengo alcun errore:

```shell
composer config extra.enable-patching true
composer config minimum-stability beta
composer config prefer-stable true
composer require italia/spid-laravel
```

Puoi provare anche tu, così vediamo se il problema è legato a qualche configurazione locale del tuo progetto?

**Comment by nicolastorgato** [comment]
Ho provato come hai detto, anche creando un nuovo progetto da zero, ma ricevo sempre questo errore:

```
$ composer require italia/spid-laravel
Using version ^0.2.0@beta for italia/spid-laravel
./composer.json has been updated
Running composer update italia/spid-laravel
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires italia/spid-laravel ^0.2.0@beta -> satisfiable by italia/spid-laravel[v0.2.0-beta].
    - italia/spid-laravel v0.2.0-beta requires illuminate/config ~5.0 -> found illuminate/config[v5.0.0, ..., v5.8.36] but these were not loaded, likely because it conflicts with another require.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

A quanto pare è un problema mio ma non riesco a capire quale. Hai qualche idea?

**Comment by pdavide** [comment]
@nicolastorgato potresti condividere un gist con il tuo `composer.json`?

**Comment by pdavide** [comment]
1. Fatto copia/incolla del tuo composer.json in una dir vuota
2. Lanciato `composer install`
3. Lanciato `composer require italia/spid-laravel`
4. Output:
```
Using version ^1.2@beta for italia/spid-laravel
./composer.json has been updated
Running composer update italia/spid-laravel
Loading composer repositories with package information
Updating dependencies
Lock file operations: 4 installs, 0 updates, 0 removals
  - Locking cweagans/composer-patches (1.7.0)
  - Locking italia/spid-laravel (v1.2.3-beta)
  - Locking onelogin/php-saml (3.4.1)
  - Locking robrichards/xmlseclibs (3.1.1)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 4 installs, 0 updates, 0 removals
  - Installing cweagans/composer-patches (1.7.0): Extracting archive
No patches supplied.
Gathering patches for dependencies. This might take a minute.
  - Installing robrichards/xmlseclibs (3.1.1): Extracting archive
  - Installing onelogin/php-saml (3.4.1): Extracting archive
  - Installing italia/spid-laravel (v1.2.3-beta): Extracting archive
  - Applying patches for onelogin/php-saml
    https://rawgit.com/italia/spid-laravel/master/patches/php-saml-3.4.1-spid.patch (Compatibility with SPID)

Generating optimized autoload files
```

Per completezza:
```shell
$ php -v
PHP 7.4.19 (cli) (built: May 13 2021 06:28:47) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.19, Copyright (c), by Zend Technologies
```

```shell
$ composer --version
Composer version 2.1.1 2021-06-04 08:46:46
```

**Comment by nicolastorgato** [comment]
L'unica differenza è che io al momento ho PHP versione 8.0.1. 

Ho provato con PHP 7.4.1 e effettivamente funziona, mi da solo questo errore: 
```
Could not apply patch! Skipping. The error was: Cannot apply patch https://rawgit.com/italia/spid-laravel/master/patches/php-saml-3.4.1-spid.patch
```

Si può tralasciare o è una cosa importante?

**Comment by pdavide** [comment]
Ciao @nicolastorgato,
il package non è stato testato con php 8.

L'errore che hai visualizzato è dovuto semplicemente al fatto che la directory con il `composer.json` era vuota quando invece doveva esserci una installazione base di laravel.

Io uso un ambiente di sviluppo dockerizzato su mac.

Se trovi ulteriori difficoltà riapri pure la issue.
