### ISSUE TITLE
Switch to spid-php-lib

### ISSUE THREAD

**Issue by pdavide** [italia/spid-laravel#8]
This package is currently based on the [php-saml](https://github.com/onelogin/php-saml) library that doesn't fully support SPID. Indeed we need a [patch](https://github.com/italia/spid-laravel/blob/master/patches/php-saml-3-spid.patch) to make it work.

We need to switch to [spid-php-lib](https://github.com/italia/spid-php-lib) which is fully compliant with SPID.

**Comment by katalyn4me** [comment]
When I install it, i get this error when the pach applying: `Could not apply patch! Skipping. The error was: Cannot apply patch https://rawgit.com/italia/spid-laravel/master/patches/php-saml-3-spid.patch`
Is this pach still required?

**Comment by pdavide** [comment]
Hi @katalyn4me,
yes the patch is still required as this package depends on `php-saml` library.
I updated the patch in cabb8ac, the issue should be fixed now.
