### ISSUE TITLE
Laravel ^10.10

### ISSUE THREAD

**Issue by jqr91** [italia/spid-laravel#97]
Salve,

ottengo il seguente errore su Laravel ^10.10:
Prima di eseguire il seguente comando: `composer require italia/spid-laravel`

ho lanciato i seguenti comandi come suggerito dalla doc

`composer config extra.enable-patching true`
`composer config minimum-stability beta`
`composer config prefer-stable true`

<img width="637" alt="Screenshot 2023-08-27 alle 15 51 31" src="https://github.com/italia/spid-laravel/assets/8181631/ce077092-ef3a-4d04-bd1b-0689032f6f55">

Potete dirmi quale versione di Laravel è consigliata con questa libreria? 

Grazie a tutti

**Comment by pdavide** [comment]
Ciao @jqr91,
il problema sembrerebbe essere la versione di PHP che stai usando. Potresti provare con PHP 8.2?

**Comment by jqr91** [comment]
Ciao, grazie ho risolto. E' compatibile con PHP 8.2.*
